const PDFDocument = require('pdfkit');

// Global channel info (to match your main.js)
const channelInfo = {
    contextInfo: {
        forwardingScore: 1,
        isForwarded: true,
        forwardedNewsletterMessageInfo: {
            newsletterJid: '120363401269012709@newsletter',
            newsletterName: 'MAD-MAX',
            serverMessageId: -1
        }
    }
};

module.exports = async function topdfCommand(client, chatId, message, args, sender, pushName, isOwner) {
    try {
        // Extract text from args
        const pdfText = args.join(' ').trim();
        
        if (!pdfText) {
            await client.sendMessage(chatId, {
                text: "╭─❖ *PDF CONVERTER* ❖─\n│\n├─ 📄 Please provide text to convert to PDF\n│\n├─ *Example:* .topdf This is my text to convert\n├─ .topdf Hello World!\n├─ .topdf Convert this paragraph to PDF file\n│\n╰─➤ _Requested by: ${pushName}_",
                ...channelInfo
            }, { quoted: message });
            return;
        }

        // Send processing reaction
        await client.sendMessage(chatId, { 
            react: { text: '⏳', key: message.key } 
        });

        // Create PDF
        const pdfBuffer = await createPDF(pdfText, pushName);

        // Send the PDF file
        await client.sendMessage(chatId, {
            document: pdfBuffer,
            mimetype: 'application/pdf',
            fileName: `document_${Date.now()}.pdf`,
            caption: `📄 *PDF created successfully!*\n\n_Requested by: ${pushName}_`,
            ...channelInfo
        }, { quoted: message });

        // Success reaction
        await client.sendMessage(chatId, { 
            react: { text: '✅', key: message.key } 
        });

    } catch (error) {
        console.error('PDF creation error:', error);
        
        await client.sendMessage(chatId, {
            text: "❌ Failed to create PDF. Please try again with different text.",
            ...channelInfo
        }, { quoted: message });

        await client.sendMessage(chatId, { 
            react: { text: '❌', key: message.key } 
        });
    }
};

// Function to create PDF from text
async function createPDF(text, requesterName) {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({
                size: 'A4',
                margins: { top: 50, bottom: 50, left: 50, right: 50 }
            });
            
            const chunks = [];
            
            // Collect PDF chunks
            doc.on('data', chunk => chunks.push(chunk));
            doc.on('end', () => resolve(Buffer.concat(chunks)));
            doc.on('error', reject);

            // Add metadata
            doc.info = {
                Title: 'MAD-MAX PDF Document',
                Author: 'MAD-MAX Bot',
                Subject: 'Text to PDF Conversion',
                Keywords: 'pdf, text, MAD-MAX, converter',
                Creator: requesterName || 'Unknown User',
                CreationDate: new Date()
            };

            // Add header
            doc.fontSize(20)
               .font('Helvetica-Bold')
               .fillColor('#2196F3')
               .text('📄 MAD-MAX PDF Document', { align: 'center' })
               .moveDown(0.5);

            doc.fontSize(10)
               .font('Helvetica')
               .fillColor('black')
               .text(`Created: ${new Date().toLocaleString()}`, { align: 'center' })
               .text(`Requested by: ${requesterName || 'User'}`, { align: 'center' })
               .moveDown(2);

            // Add content
            doc.fontSize(12)
               .font('Helvetica-Bold')
               .fillColor('#4CAF50')
               .text('Content:', { underline: true })
               .moveDown(0.5);

            doc.fontSize(11)
               .font('Helvetica')
               .fillColor('black')
               .text(text, {
                    align: 'left',
                    lineGap: 5,
                    paragraphGap: 10,
                    indent: 20,
                    width: 500,
                    columns: 1
               })
               .moveDown(2);

            // Add footer
            const pageWidth = doc.page.width;
            const pageHeight = doc.page.height;
            
            doc.fontSize(9)
               .font('Helvetica-Oblique')
               .fillColor('#666666')
               .text('Generated by MAD-MAX Bot', 50, pageHeight - 50, {
                    align: 'center',
                    width: pageWidth - 100
               });

            // Add page numbers
            const pages = doc.bufferedPageRange ? doc.bufferedPageRange().count : 1;
            for (let i = 0; i < pages; i++) {
                doc.switchToPage(i);
                doc.fontSize(8)
                   .fillColor('#999999')
                   .text(
                        `Page ${i + 1} of ${pages}`,
                        doc.page.width - 100,
                        doc.page.height - 50,
                        { align: 'right', width: 50 }
                   );
            }

            // Finalize
            doc.end();

        } catch (error) {
            reject(error);
        }
    });
}